### ISSUE TITLE
not working with react-native 0.33.0

### ISSUE THREAD

**Issue by karpoff** [doomsower/react-native-vkontakte-login#7]
Hi

after upgrading to react-native 0.33.0 project build (android) fails with

> :react-native-vkontakte-login:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
<project>\node_modules\react-native-vkontakte-login\android\src\main\java\camp\kuznetsov\rn\vkontakte\VKAuthModule.java:17: error: VKAuthModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class VKAuthModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
<project>\node_modules\react-native-vkontakte-login\android\src\main\java\camp\kuznetsov\rn\vkontakte\VKAuthModule.java:109: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-vkontakte-login:compileReleaseJavaWithJavac FAILED

Could you fix it?
and thank you for great module

**Comment by karpoff** [comment]
it works now.
thanks for quick fix!
